
Collecting tasks from: tasks.py
=================== Running: [96morder_robots_from_RobotSpareBin[0m ===================
File DataSets\orders.csv has been deleted successfully.
File DataSets\orders.csv has been deleted successfully.
    Order number  Head  Body  Legs      Address
0              1     1     2     3  Address 123
1              2     4     1     5  Address 456
2              3     6     2     3  Address 789
3              4     2     3     2    Address 1
4              5     3     5     1    Address 2
5              6     1     6     6    Address 3
6              7     5     1     5    Address 4
7              8     2     3     3    Address 5
8              9     3     2     2    Address 6
9             10     4     4     2    Address 7
10            11     6     6     1    Address 8
11            12     1     3     3    Address 9
12            13     1     5     4    Address A
13            14     3     1     5    Address B
14            15     3     2     6    Address C
15            16     6     3     6    Address D
16            17     5     4     1    Address E
17            18     2     5     1    Address F
18            19     4     6     2    Address G
19            20     1     1     5    Address H
0 1
1 2
2 3
Server error message detected, proceeding to click 'Order' again
3 4
Server error message detected, proceeding to click 'Order' again
Server error message detected, proceeding to click 'Order' again
4 5
5 6
6 7
Server error message detected, proceeding to click 'Order' again
7 8
8 9
9 10
10 11
11 12
Server error message detected, proceeding to click 'Order' again
12 13
13 14
14 15
15 16
16 17
Server error message detected, proceeding to click 'Order' again
17 18
18 19
19 20
[96morder_robots_from_RobotSpareBin[0m status: PASS
================================================================================
Robocorp Log (html): c:\Users\jeppsvig\OneDrive - Tietoevry\Robocorp RPA\Robots\PythonCert_2\output\log.html
